### ISSUE TITLE
nitty run does not run...

### ISSUE THREAD

**Issue by ycorrales** [cbourjau/nittygriddy#23]
nitty run grid returns a "DeprecationWarning: TTL should be ... " and does not go on.

**Comment by cbourjau** [comment]
Ups, sorry about that! This was introduced in commit 171646106cef5fb4e9982afbb1910b9425ff92b3 . The idea is that TTL in seconds is kind of a pain to work with. I'll push a fix in a moment

**Comment by cbourjau** [comment]
Should be fixed now. Thanks for reporting!
